export default {
    list: [
    {
        type: 1,
        title: "Cobertores de inverno",
        description: "Lorem ipsum...",
        images: [  "https://placekitten.com/370/370", 
                    "https://placekitten.com/300/300", 
                    "http://placerabbit.com/200/333",
                    "http://placerabbit.com/g/333/333"],
        anonymous: false,
        category: "Agasalho",
        user: {
            name: "Paulo",
            avatar: "http://placerabbit.com/g/200/200",
            telefone: "(75) 3422-1999",
            local: "Alagoinhas-BA",
        },
        type: 1,
        title: "Cobertores de verão",
        description: "Lorem ipsum...",
        images: [  "https://placekitten.com/370/370", 
                    "https://placekitten.com/300/300", 
                    "http://placerabbit.com/200/333",
                    "http://placerabbit.com/g/333/333"],
        anonymous: false,
        category: "Agasalho",
        user: {
            name: "Paulo",
            avatar: "http://placerabbit.com/g/200/200",
            telefone: "(75) 3422-1999",
            local: "Alagoinhas-BA",
        },
        type: 1,
        title: "Geladeira",
        description: "Lorem ipsum...",
        images: [  "https://placekitten.com/370/370", 
                    "https://placekitten.com/300/300", 
                    "http://placerabbit.com/200/333",
                    "http://placerabbit.com/g/333/333"],
        anonymous: false,
        category: "Agasalho",
        user: {
            name: "Paulo",
            avatar: "http://placerabbit.com/g/200/200",
            telefone: "(75) 3422-1999",
            local: "Alagoinhas-BA",
        },
        type: 1,
        title: "Puppy",
        description: "Lorem ipsum...",
        images: [  "https://placekitten.com/370/370", 
                    "https://placekitten.com/300/300", 
                    "http://placerabbit.com/200/333",
                    "http://placerabbit.com/g/333/333"],
        anonymous: false,
        category: "Animals",
        user: {
            name: "Paulo",
            avatar: "http://placerabbit.com/g/200/200",
            telefone: "(75) 3422-1999",
            local: "Alagoinhas-BA",
        },
        type: 1,
        title: "Fogão de 5 bocas",
        description: "Lorem ipsum...",
        images: [  "https://placekitten.com/370/370", 
                    "https://placekitten.com/300/300", 
                    "http://placerabbit.com/200/333",
                    "http://placerabbit.com/g/333/333"],
        anonymous: false,
        category: "Agasalho",
        user: {
            name: "Paulo",
            avatar: "http://placerabbit.com/g/200/200",
            telefone: "(75) 3422-1999",
            local: "Alagoinhas-BA",
        },
        type: 1,
        title: "Forno de microondas",
        description: "Lorem ipsum...",
        images: [  "https://placekitten.com/370/370", 
                    "https://placekitten.com/300/300", 
                    "http://placerabbit.com/200/333",
                    "http://placerabbit.com/g/333/333"],
        anonymous: false,
        category: "Eletro",
        user: {
            name: "Paulo",
            avatar: "http://placerabbit.com/g/200/200",
            telefone: "(75) 3422-1999",
            local: "Alagoinhas-BA",
        },
        type: 1,
        title: "Casinha de cachorro",
        description: "Lorem ipsum...",
        images: [  "https://placekitten.com/370/370", 
                    "https://placekitten.com/300/300", 
                    "http://placerabbit.com/200/333",
                    "http://placerabbit.com/g/333/333"],
        anonymous: false,
        category: "Lazer",
        user: {
            name: "Paulo",
            avatar: "http://placerabbit.com/g/200/200",
            telefone: "(75) 3422-1999",
            local: "Alagoinhas-BA",
        },
        type: 2,
        title: "Cobertores de inverno",
        description: "Lorem ipsum...",
        images: [  "https://placekitten.com/370/370", 
                    "https://placekitten.com/300/300", 
                    "http://placerabbit.com/200/333",
                    "http://placerabbit.com/g/333/333"],
        anonymous: false,
        category: "Agasalho",
        user: {
            name: "Paulo",
            avatar: "http://placerabbit.com/g/200/200",
            telefone: "(75) 3422-1999",
            local: "Alagoinhas-BA",
        },
        type: 1,
        title: "Cobertores de inverno",
        description: "Lorem ipsum...",
        images: [  "https://placekitten.com/370/370", 
                    "https://placekitten.com/300/300", 
                    "http://placerabbit.com/200/333",
                    "http://placerabbit.com/g/333/333"],
        anonymous: false,
        category: "Agasalho",
        user: {
            name: "Paulo",
            avatar: "http://placerabbit.com/g/200/200",
            telefone: "(75) 3422-1999",
            local: "Alagoinhas-BA",
        },
        type: 1,
        title: "Cobertores de inverno",
        description: "Lorem ipsum...",
        images: [  "https://placekitten.com/370/370", 
                    "https://placekitten.com/300/300", 
                    "http://placerabbit.com/200/333",
                    "http://placerabbit.com/g/333/333"],
        anonymous: false,
        category: "Agasalho",
        user: {
            name: "Paulo",
            avatar: "http://placerabbit.com/g/200/200",
            telefone: "(75) 3422-1999",
            local: "Alagoinhas-BA",
        },
        type: 2,
        title: "Cobertores de inverno",
        description: "Lorem ipsum...",
        images: [  "https://placekitten.com/370/370", 
                    "https://placekitten.com/300/300", 
                    "http://placerabbit.com/200/333",
                    "http://placerabbit.com/g/333/333"],
        anonymous: false,
        category: "Agasalho",
        user: {
            name: "Paulo",
            avatar: "http://placerabbit.com/g/200/200",
            telefone: "(75) 3422-1999",
            local: "Alagoinhas-BA",
        },
        type: 1,
        title: "Cobertores de inverno",
        description: "Lorem ipsum...",
        images: [  "https://placekitten.com/370/370", 
                    "https://placekitten.com/300/300", 
                    "http://placerabbit.com/200/333",
                    "http://placerabbit.com/g/333/333"],
        anonymous: false,
        category: "Agasalho",
        user: {
            name: "Paulo",
            avatar: "http://placerabbit.com/g/200/200",
            telefone: "(75) 3422-1999",
            local: "Alagoinhas-BA",
        },
        type: 2,
        title: "Cobertores de inverno",
        description: "Lorem ipsum...",
        images: [  "https://placekitten.com/370/370", 
                    "https://placekitten.com/300/300", 
                    "http://placerabbit.com/200/333",
                    "http://placerabbit.com/g/333/333"],
        anonymous: false,
        category: "Agasalho",
        user: {
            name: "Paulo",
            avatar: "http://placerabbit.com/g/200/200",
            telefone: "(75) 3422-1999",
            local: "Alagoinhas-BA",
        },
        type: 1,
        title: "Cobertores de inverno",
        description: "Lorem ipsum...",
        images: [  "https://placekitten.com/370/370", 
                    "https://placekitten.com/300/300", 
                    "http://placerabbit.com/200/333",
                    "http://placerabbit.com/g/333/333"],
        anonymous: false,
        category: "Agasalho",
        user: {
            name: "Paulo",
            avatar: "http://placerabbit.com/g/200/200",
            telefone: "(75) 3422-1999",
            local: "Alagoinhas-BA",
        },
        type: 2,
        title: "Cobertores de inverno",
        description: "Lorem ipsum...",
        images: [  "https://placekitten.com/370/370", 
                    "https://placekitten.com/300/300", 
                    "http://placerabbit.com/200/333",
                    "http://placerabbit.com/g/333/333"],
        anonymous: false,
        category: "Agasalho",
        user: {
            name: "Paulo",
            avatar: "http://placerabbit.com/g/200/200",
            telefone: "(75) 3422-1999",
            local: "Alagoinhas-BA",
        },
        type: 1,
        title: "Cobertores de inverno",
        description: "Lorem ipsum...",
        images: [  "https://placekitten.com/370/370", 
                    "https://placekitten.com/300/300", 
                    "http://placerabbit.com/200/333",
                    "http://placerabbit.com/g/333/333"],
        anonymous: false,
        category: "Agasalho",
        user: {
            name: "Paulo",
            avatar: "http://placerabbit.com/g/200/200",
            telefone: "(75) 3422-1999",
            local: "Alagoinhas-BA",
        },
        
    },
]}